sambamba/sort.d
Artem;
On busy NFS filesystems, removal of temporary directories can fail due to NFS having a lock on files. This avoids erroring out in this situation. (lomereiter/sambamba#124 chapmanb/bcbio-nextgen#784).
I found a reproducible case and confirmed this fix resolves it. If anyone would like to test, there is a pre-built linux executable of the latest head plus this fix at (https://s3.amazonaws.com/cloudbiolinux/cache/sambamba_0.5.2a-2015-03-18) and a brew recipe (https://github.com/chapmanb/homebrew-cbl/blob/master/sambamba-binary.rb). Thanks much.
=> Avoid NFS errors when removing temporary directories after sort

sambamba/pileup.d
We noticed that in general mpileup shows suboptimtal thread utilisation
(issue #237). Ordering of output results is currently the responsibility
of worker threads, so many of the are waiting on the condition variable
of ChunkDispatcher.
This patch closes #237 by:
* Queueing results in a min heap.
* Writing from queue to file via a separate thread.
* Allowing worker threads to process subsequent chunks immediately.
* Moderately increasing in memory usage for short queues.
We currently see that the output thread cannot keep up with the workers,
leading to large increases in memory and runtime due to queueing, even
though processing time is decreased and thread utilisation is
full. Using a lower thread count would of course alleviate this but the
cause is not completely clear. This could be …
=> Queue completed pileup chunk results, allowing out-of-sequence workers to continue

sambamba/pileup.d
On specific BAM sets the output thread was hanging on an empty queue after dumping all chunks successfully dependent on load and thread scheduling.
The correction is based on using the total number of chunks as termination condition for the dump thread instead of the queue content and an indication for running workers. To avoid a hanging queuing thread in case of exceptions and unnecessary delay of program termination the join conditions for the workers and the dump thread were moved from the exit scope to the success branch at the end of the main function.
=> Correction for hanging dump thread - #242

sambamba/sort.d
* continue with the currently allocated memory
* warn continuously (maybe not ideal?)
=> Warn when running out of memory instead of segfaulting

sambamba/pileup.d
@nosepy @sambrightman does it make sense to still keep queue length limit with this change?
=> Queue total data size limit

Makefile, gen_ldc_version_info.py
* always re-generate the LDC version info
* allow bootstrap version to be optional (for older LDC versions)
* fail with an error message if version parsing fails
=> Fix some corner-cases from #259

sambamba/pileup.d, sambamba/utils/common/bed.d, utils/version_.d
1. Prepared samtools/bcftools integration for GNU Guix - simplified logic somewhat
2. Fixed a number of compiler warnings
3. Fixed --bcftools switch without arguments (as promised in manual)
4. Bump version
=> pileup.d fixes

.gitignore, .gitmodules, .travis.yml, Makefile, README.md, gen_ldc_version_info.py
Test build with nix on Archlinux with following kernel
$ uname -a
Linux aurae 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux
$ gcc --version
gcc (GCC) 6.4.0
$  ldc2 --version
LDC - the LLVM D compiler (1.3.0):
based on DMD v2.073.2 and LLVM 4.0.1
built with DMD64 D Compiler v2.075.1
I pulled the latest undeaD commit (7bdc188) since there is no information regarding which commit was previously used.
=> Fix compilation error on Linux

sambamba/markdup.d
This is a resolution to #326 and also something we observed internally (https://github.com/maxplanck-ie/snakepipes/issues/233 ) where markdup is limited to files with <=16383 contigs. This PR modifies the size of the structures such that all BAM files should be supported, regardless of the number of contigs/scaffolds.
In my tests this produces identical results on files already supported by `sambamba markdup`, while requiring a small (10-20% peak) increase in RAM. There's no appreciable run-time difference that I've seen.
=> Mark duplicates in files with many contigs

sambamba/flagstat.d
flagstat is the only tool that isn't returning 1 when errors are encountered.  This adds the return 1 to the catch block.
=> return 1 on error

sambamba/sort.d
When one passes a float, let's say -m=2.5G the only message that is returned is: "sambamba-sort: couldn't parse ", which is not very informative, as this someone may blame the input BAM file and spend some time trying to figure out what is wrong with it. The updated error message points directly to the problem. That's a very little change that may save some time.
=> make error message more informative

INSTALL.md, gen_ldc_version_info.py, scripts/bioconda_push.sh, scripts/bioconda_yaml_gen.py, test/test_depth.py
Hi!
We are currently working on [removing Python 2](https://lists.debian.org/debian-python/2019/07/msg00080.html) from Debian, and all other Linux distributions are working on similar efforts.
While it's likely that at some point Debian will provide a "python" binary pointing to the latest Python version, for now "python" still means Py2 and that executable will likely be gone soon (hopefully in time for the next Debian release).
This patch makes Sambamba use python3 explicitly wherever possible.
I don't know much about Guix, so the Guix packages line may need to be adjusted differently (please have a look at that).
Cheers,
Matthias
=> Always use Python 3+

.gitignore, meson.build, meson_options.txt
Hi!
As written in my mail, here's the Meson build definition. It's not 100% what we use at Debian, because this definition was adjusted for the current upstream code and also has a flag to disable tests for faster building.
The project can be built with Meson using these commands:
```bash
mkdir build && cd build
meson .. # pass --buildtype=debugoptimized -Doptimize_strong=true for strongest optimizations
ninja # parallel build
ninja test
```
To skip building tests and save a bit of build time, `-Dtests=false` can be passed as an option when configuring the build.
The build requires BioD to be installed system-wide first (there is an option to use Meson subprojects to automatically fetch it and bake it in, but I did skip that implementation - if you want it, it would be quite easy to do …
=> Add Meson build definition

INSTALL.md
This partially reverts https://github.com/biod/sambamba/pull/418 as [my suggestion there](https://github.com/biod/sambamba/pull/418/files#r358093099) was ignored before merging.
Also note that as of now, the `guix package` and `guix environment` calls don't match.
=> Fix GNU Guix install instructions

sambamba/flagstat.d
I added an option to flagstat to output in csv format
I was trying to consolidate flagstat output from many bam files into a clean summary table. A csv format file makes it much easier and less error prone.
Used option: -b/--tabular
output format:
description, param[0], param[1]
description, param[0]:percent(param[0]), param[1]:(percent(param[1]))
=> Add option to output in csv format

BioD/bio/std/hts/sam/header.d
This PR adds missing standard header tags which are listed in the current (as of January, 2021) SAM specification (http://samtools.github.io/hts-specs/SAMv1.pdf).
Fixes #462 but does not allow "freely add new tags for further data fields", as it is allowed by the SAM specification.
=> add missing standard SAM header tags

Makefile
In some environments (i. e. Ubuntu 18.04 and 20.04 with LDC v1.8) `make static` fails with the following error message:
```
Error: Can't use -link-defaultlib-shared and -static together
Makefile:89: recipe for target 'singleobj' failed
make: *** [singleobj] Error 1
```
This PR just disables the linking of default shared libs, which is intentional on static builds.
=> disable linking of default shared libs on static build

Makefile, Makefile.guix
This is to fix a downstream error in Nix on macOS: https://hydra.nixos.org/build/142939840/nixlog/3
=> Fix build when GCC is not installed

BioD/bio/std/experimental/hts/bam/reader.d, BioD/bio/std/experimental/hts/bgzf.d, BioD/bio/std/experimental/hts/pileup.d, sambamba/markdup.d, sambamba/pileup.d, sambamba/subsample.d
Motivation: I want to update LDC in Nix package repository.
The `alias this` of `std.typecons.Nullable` has been removed and now explicit `.get`s are required.
=> Made compile with removed alias this in Nullable

.github/workflows/ci.yaml
It seems [TravisCI](https://app.travis-ci.com/github/biod/sambamba) hasn't be used since 6d6295de45e5561936894692bb8afa8c9a233cba (May 22 2021), i.e. around 30 commits have been not tested!
With this PR I suggest moving to Github Actions.
The benefits are:
1) TravisCI is no more free for open source projects
2) Github Actions (GHA) is maintained better. There are many "actions" provided by the community
3) it could be used to release binaries for x86_64, aarch64 and more. The non-x86_64 builds are run on QEMU but this seems to be working quite well for Sambamba!
A green build could be seen in my fork - https://github.com/martin-g/sambamba/actions/runs/3250757265
And binary artifacts at https://github.com/martin-g/sambamba/suites/8778990966/artifacts/398461533
With the help of this …
=> Add CI config for Github Actions
